//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.ItemOrders = new HashSet<ItemOrder>();
        }
    
        public int idBill { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> paymenttime { get; set; }
        public Nullable<bool> thanhtoan { get; set; }
        public int idTable { get; set; }
        public int idAccount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TableFood TableFood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemOrder> ItemOrders { get; set; }
    }
}
