//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrder
    {
        public int idorder { get; set; }
        public Nullable<int> idBill { get; set; }
        public Nullable<int> idFood { get; set; }
        public Nullable<int> billquantity { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Food Food { get; set; }
    }
}
