//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int idFood { get; set; }
        public string NameFood { get; set; }
        public Nullable<int> idCategory { get; set; }
        public double price { get; set; }
    
        public virtual FoodCategory FoodCategory { get; set; }
    }
}
